# Generated by Django 4.0.3 on 2023-02-04 07:06

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('cat_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('ststus', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('meta_titile', models.TextField(max_length=500)),
                ('meta_desc', models.TextField(max_length=500)),
                ('meta_keywords', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('prod_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('small_desc', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('ststus', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_titile', models.CharField(max_length=150)),
                ('meta_desc', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
